
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.implementacionparser;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class theParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return theParserSym.class;
}

  /** Default constructor. */
  @Deprecated
  public theParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public theParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public theParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\012\000\002\002\004\000\002\002\004\000\002\003" +
    "\005\000\002\003\002\000\002\004\004\000\002\005\005" +
    "\000\002\005\002\000\002\006\003\000\002\006\003\000" +
    "\002\006\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\022\000\010\004\011\010\004\011\010\001\002\000" +
    "\012\002\ufff9\005\ufff9\006\ufff9\007\ufff9\001\002\000\010" +
    "\002\ufffe\005\ufffe\006\022\001\002\000\012\002\ufffb\005" +
    "\ufffb\006\ufffb\007\016\001\002\000\004\002\014\001\002" +
    "\000\012\002\ufffa\005\ufffa\006\ufffa\007\ufffa\001\002\000" +
    "\010\004\011\010\004\011\010\001\002\000\004\005\013" +
    "\001\002\000\012\002\ufff8\005\ufff8\006\ufff8\007\ufff8\001" +
    "\002\000\004\002\000\001\002\000\010\002\ufffd\005\ufffd" +
    "\006\ufffd\001\002\000\010\004\011\010\004\011\010\001" +
    "\002\000\012\002\ufffb\005\ufffb\006\ufffb\007\016\001\002" +
    "\000\010\002\ufffc\005\ufffc\006\ufffc\001\002\000\006\002" +
    "\001\005\001\001\002\000\010\004\011\010\004\011\010" +
    "\001\002\000\010\002\ufffe\005\ufffe\006\022\001\002\000" +
    "\006\002\uffff\005\uffff\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\022\000\010\002\006\004\004\006\005\001\001\000" +
    "\002\001\001\000\004\003\020\001\001\000\004\005\014" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\002" +
    "\011\004\004\006\005\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\006" +
    "\016\001\001\000\004\005\017\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\004\022\006\005\001\001\000" +
    "\004\003\023\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$theParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$theParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$theParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public TheParser (lexer_Figuras lexer){//Esto no es necesario pues el lexer.java extiende de Scanner
        super(lexer);
        recolectorFiguras = new RecolectorFiguras();/*agregado*/
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$theParser$actions {
  private final theParser parser;

  /** Constructor */
  CUP$theParser$actions(theParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$theParser$do_action_part00000000(
    int                        CUP$theParser$act_num,
    java_cup.runtime.lr_parser CUP$theParser$parser,
    java.util.Stack            CUP$theParser$stack,
    int                        CUP$theParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$theParser$result;

      /* select the action based on the action number */
      switch (CUP$theParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // E ::= T Ep 
            {
              Object RESULT =null;

              CUP$theParser$result = parser.getSymbolFactory().newSymbol("E",0, ((java_cup.runtime.Symbol)CUP$theParser$stack.elementAt(CUP$theParser$top-1)), ((java_cup.runtime.Symbol)CUP$theParser$stack.peek()), RESULT);
            }
          return CUP$theParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= E EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$theParser$stack.elementAt(CUP$theParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$theParser$stack.elementAt(CUP$theParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$theParser$stack.elementAt(CUP$theParser$top-1)).value;
		RESULT = start_val;
              CUP$theParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$theParser$stack.elementAt(CUP$theParser$top-1)), ((java_cup.runtime.Symbol)CUP$theParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$theParser$parser.done_parsing();
          return CUP$theParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Ep ::= Suma T Ep 
            {
              Object RESULT =null;

              CUP$theParser$result = parser.getSymbolFactory().newSymbol("Ep",1, ((java_cup.runtime.Symbol)CUP$theParser$stack.elementAt(CUP$theParser$top-2)), ((java_cup.runtime.Symbol)CUP$theParser$stack.peek()), RESULT);
            }
          return CUP$theParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Ep ::= 
            {
              Object RESULT =null;

              CUP$theParser$result = parser.getSymbolFactory().newSymbol("Ep",1, ((java_cup.runtime.Symbol)CUP$theParser$stack.peek()), RESULT);
            }
          return CUP$theParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // T ::= F Tp 
            {
              Object RESULT =null;

              CUP$theParser$result = parser.getSymbolFactory().newSymbol("T",2, ((java_cup.runtime.Symbol)CUP$theParser$stack.elementAt(CUP$theParser$top-1)), ((java_cup.runtime.Symbol)CUP$theParser$stack.peek()), RESULT);
            }
          return CUP$theParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Tp ::= Por F Tp 
            {
              Object RESULT =null;

              CUP$theParser$result = parser.getSymbolFactory().newSymbol("Tp",3, ((java_cup.runtime.Symbol)CUP$theParser$stack.elementAt(CUP$theParser$top-2)), ((java_cup.runtime.Symbol)CUP$theParser$stack.peek()), RESULT);
            }
          return CUP$theParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Tp ::= 
            {
              Object RESULT =null;

              CUP$theParser$result = parser.getSymbolFactory().newSymbol("Tp",3, ((java_cup.runtime.Symbol)CUP$theParser$stack.peek()), RESULT);
            }
          return CUP$theParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // F ::= Identificador 
            {
              Object RESULT =null;

              CUP$theParser$result = parser.getSymbolFactory().newSymbol("F",4, ((java_cup.runtime.Symbol)CUP$theParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$theParser$stack.peek()), RESULT);
            }
          return CUP$theParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // F ::= Numero 
            {
              Object RESULT =null;

              CUP$theParser$result = parser.getSymbolFactory().newSymbol("F",4, ((java_cup.runtime.Symbol)CUP$theParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$theParser$stack.peek()), RESULT);
            }
          return CUP$theParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // F ::= Parentesis_abierto E Parentesis_cerrado 
            {
              Object RESULT =null;

              CUP$theParser$result = parser.getSymbolFactory().newSymbol("F",4, ((java_cup.runtime.Symbol)CUP$theParser$stack.elementAt(CUP$theParser$top-2)), ((java_cup.runtime.Symbol)CUP$theParser$stack.peek()), RESULT);
            }
          return CUP$theParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$theParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$theParser$do_action(
    int                        CUP$theParser$act_num,
    java_cup.runtime.lr_parser CUP$theParser$parser,
    java.util.Stack            CUP$theParser$stack,
    int                        CUP$theParser$top)
    throws java.lang.Exception
    {
              return CUP$theParser$do_action_part00000000(
                               CUP$theParser$act_num,
                               CUP$theParser$parser,
                               CUP$theParser$stack,
                               CUP$theParser$top);
    }
}

}
