
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.implementacionparser;

/** CUP generated class containing symbol constants. */
public class theParserSym {
  /* terminals */
  public static final int Numero = 6;
  public static final int error = 1;
  public static final int Parentesis_cerrado = 3;
  public static final int Por = 5;
  public static final int Identificador = 7;
  public static final int Suma = 4;
  public static final int Parentesis_abierto = 2;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Parentesis_abierto",
  "Parentesis_cerrado",
  "Suma",
  "Por",
  "Numero",
  "Identificador"
  };
}

